### ISSUE TITLE
readme.md on prometheus-grafana has broken link

### ISSUE THREAD

**Issue by gamba47** [docker/awesome-compose#136]
Hi guys, this is a silly problem

The link in this readme.md https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/README.md points to a broken link https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/docker-compose.yaml

I don't know the working link only use the link in the same path https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/docker-compose.yml and it's working.

Nice work!

**Comment by dineshkumar12004** [comment]
can i work on this issue ?

**Comment by dineshkumar12004** [comment]
Made a pull request. Love to know the feedback on this PR.

**Comment by dineshkumar12004** [comment]
close this issue please.
