### ISSUE TITLE
ERROR: "/workdir/server/target/dependency/BOOT-INF/lib" not found: not found

### ISSUE THREAD

**Issue by gguiboux** [docker/awesome-compose#144]
Hi,

I followed the awesome-compose spring-postgres repo. 
When i try to buid spring api Docker file, i've got this error : 

#16 ERROR: "/workdir/server/target/dependency/BOOT-INF/lib" not found: not found
------
 > [stage-1 2/4] COPY --from=builder /workdir/server/target/dependency/BOOT-INF/lib /app/lib:
------
------
 > [stage-1 3/4] COPY --from=builder /workdir/server/target/dependency/META-INF /app/META-INF:
------
------
 > [stage-1 4/4] COPY --from=builder /workdir/server/target/dependency/BOOT-INF/classes /app:
------
failed to compute cache key: "/workdir/server/target/dependency/BOOT-INF/classes" not found: not found
Service 'api' failed to build

Can you tell me what i didwrong ?
Thank you

**Comment by glours** [comment]
To run this sample, you just need to go to the sample directory
```shell
$ cd spring-postgres
```
And then just do a `compose up`, Docker Compose will build the image for you
```shell
$ docker-compose up -d
```

**Comment by gguiboux** [comment]
thanx
