### ISSUE TITLE
Awesome-compose as an apt package

### ISSUE THREAD

**Issue by kouul** [docker/awesome-compose#36]
It would be good to have awesome-compose as a package that is easy to install for everyone.

For instance, if I want to install it I could just use: 
> $ apt-get install awesome-compose or awesome-docker-compose

don't mind the name, I am just suggesting name that could go along.

And, if I want to use it(I will take flask as an example here), I could use:
> $ awesome-compose flask
-- with nginx: I would simply add argument like -nx
-- with mongo: I would simply add -mg

So when I run awesome-compose flask -nx -mg, this would result in creation of the folder 'nginx-flask-mongo' that is in this repo.

Is this do-able? What are your thoughts?

**Comment by justincormack** [comment]
I think apt is harder to install for most people, as it only works on Debian/Ubuntu, while `https://github.com/docker/awesome-compose.git` works for anyone on any platform. You could have a CLI to run it but these are samples and designed to be run with Docker Compose.

**Comment by OneCricketeer** [comment]
What exactly is there to install? There's no binaries here. If anything, each "folder" would be more appropriate as a submodule for anyone to clone individually. 

This is a model similar to Spring Initializr

**Comment by mikesir87** [comment]
Hi all! We're going to close this issue due to inactivity and that it is not on our roadmap. There are a variety of ways to consume the project today, minimizing the need for an apt package.

If you have further ideas for enhancements, feel free to open a new issue. Thanks!
