### ISSUE TITLE
Express / MongoDB example

### ISSUE THREAD

**Issue by SEdilson** [docker/awesome-compose#50]
I was looking at the repo and haven't found any example using express with mongo and since this is a ordinary stack for JS developers i believe it could be really helpful.

**Comment by glours** [comment]
@SEdilson there's now a sample with React, Express and Mongo thanks to @123afzal !

**Comment by 123afzal** [comment]
Thanks for mention @glours , I'm glad to be working on such a great technology that is backed by a great & active  community
