### ISSUE TITLE
How is this different from how compose worked years back?

### ISSUE THREAD

**Issue by pentago** [docker/awesome-compose#54]
How is this different from how compose worked years back?

**Comment by glours** [comment]
There's no differences 😉 
This repository is a collection of ready to use samples with different kind of technologies

**Comment by pentago** [comment]
Its kind of pathetic that its made just now.
Why not 5 years ago? Regardless of the answer nobody serious and in sane mind will use docker compose in production nowadays over Kubernetes Yamls, Kustomize, J/ksonnet.

I dont get this move a slightest bit but okay for those just starting.

**Comment by glours** [comment]
> "but okay for those just starting" 
This repo is exactly for those starting with docker-compose

[The compose specification](https://compose-spec.io/) has been open sourced this week, let's see what can happen

**Comment by OneCricketeer** [comment]
fwiw, I agree with sentiment that Fig/Compose should have taken off a lot more than "just recently"

> Regardless of the answer nobody serious and in sane mind will use docker compose in production nowadays over Kubernetes Yamls, Kustomize, J/ksonnet

1. I suggest you look at https://kelda.io
2. Given that the spec is open sourced and becoming standardized, it opens up the market for people to parse Compose object models into other schedulers (not only k8s). For example, Kompose does exactly that
