### ISSUE TITLE
docker-compsose for jenkins, nginx, node with pm2

### ISSUE THREAD

**Issue by sujeet-agrahari** [docker/awesome-compose#72]
I want need to deploy an node app and integrate jenkins, this is what I have developed so far.

Docker compose file will start three services. 
1. Jenkins
2. Nginx
3. An image from Dockerfile. This will be the node app.
 This node app will run on port 3000:3000 and nignx will be forwarding all the request to this port `http://localhost:3000`

From jenkins dashboard. I will ssh into the node-app container, and it will fetch the repo from github.

**Comment by vmtlw** [comment]
`sudo apt-get install mc uget htop `

**Comment by imjerri** [comment]
closed??
