### ISSUE TITLE
I want to become a software developer using C++ , I just need some advice from experts. Thanks

### ISSUE THREAD

**Issue by yesitsrafid** [docker/awesome-compose#90]
Hi,
My name is Rezwan Rafid. I am 17 years old now. I have a dream of becoming a Software Developer. So, I choose C++ to start. I started learning to code, but for some reason, I felt I was lagging. I thought only using C++ I can't build good quality user-friendly softs. So, I am in darkness right now. If any expert can give any tips.

**Comment by glours** [comment]
Hi @yesitsrafid 
I don't think `awesome-compose` is the right place for your question
Start to learn algorithmic first on Mooc platform for example
