### ISSUE TITLE
Idea-Proposal

### ISSUE THREAD

**Issue by rounaksarda** [docker/awesome-compose#98]
Hello, 

I am a beginner, I want to make docker-compose for a spring-boot app with MYSQL database, I may need some help for the same if allowed to do so, as I am a beginner. I have an example application for the same which you can see, [Spring Boot Petclinic](https://github.com/spring-projects/spring-petclinic). Looking forward to hear back.

Thanks!

**Comment by frgreiner** [comment]
Have a look at the [React / Java / MySQL](https://github.com/docker/awesome-compose/tree/master/react-java-mysql) example, it already includes a spring-boot backend with a MySQL database. It should provide you with all the configuration you need to get your project ready for docker-compose.

I don't think an additional example for a spring-boot app with a MySQL database is necessary, as the configuration would be the same. Just remove the react frontend and add the port binding for the backend service instead ...

**Comment by rounaksarda** [comment]
> Have a look at the [React / Java / MySQL](https://github.com/docker/awesome-compose/tree/master/react-java-mysql) example, it already includes a spring-boot backend with a MySQL database. It should provide you with all the configuration you need to get your project ready for docker-compose.
> 
> I don't think an additional example for a spring-boot app with a MySQL database is necessary, as the configuration would be the same. Just remove the react frontend and add the port binding for the backend service instead ...
